### ISSUE TITLE
🤸 Select Blend URI option

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Blending#10]
_Issue moved from Website repository: https://github.com/Starcounter/Website/issues/234_

In Content app I use the id for URIs (ex: `/content/dynamic/Cq`).

In version 1 of Content app, the user had the possibility to write the URIs that he/she desires (after `/content/dynamic/`), but I changed this because now a Content Item can have a `Name` and there can be multiple Content Items with the same name (especially if the parent content item is different. For example, "Introduction" can be a content item name that is repeating).

So at this moment the user has to select the URI that is provided when he/she creates a new content item and copy it to "Blend URI". I don't find this very friendly.

I was thinking about having a combo box for Blend URI, maybe? (with displays like `/content/dynamic/Cq ({ContentItemName})` if the values are from `Simplified.Ring6.WebContent`)
What do you think?

**Comment by warpech** [comment]
@kegor could you please check if there is an API that allows us to get a list of currently declared URIs? It should be the same list that is used to populate http://localhost:8181/#/server/network. If you can't find it, please ask @alemoi.

**Comment by kegor** [comment]
@warpech you mean something like http://127.0.0.1:8181/gw/stats?

**Comment by warpech** [comment]
Yes, but you want a C# method that returns a list of those, not a REST API call.

**Comment by kegor** [comment]
@warpech I found one example here https://github.com/Starcounter/level1/blob/2ee996fbbd7c5201d2b82d3c8c7493569ab237db/src/Programs/Starcounter.TrayIcon/Service/NetworkTask.cs#L21.

**Comment by warpech** [comment]
I was rather thinking of [GetRegisteredHandlers](https://github.com/Starcounter/level1/blob/cb13897cb2352deb726d91e2463340e28b45d234/src/Starcounter.Internal/Handle.cs#L470) which seems to be publicly exposed, but not documented. @alemoi can we use that?

**Comment by alemoi** [comment]
> @alemoi can we use that?

Sure but it will give you handlers for current codehost/database, not all.

**Comment by Mihaiii** [comment]
Content app is blocking the original issue that was opened by me in Website app.
I really appreciate what @warpech did (I'm not sure if it was intentional or as a side effect) and I'd like to announce that Content app will be fixed by monday for SC 2.4, in case this will change anything regarding this current issue.

**Comment by warpech** [comment]
> Sure but it will give you handlers for current codehost/database, not all.

That's completely understandable, thanks. It is enough.

> Content app is blocking the original issue that was opened by me in Website app.
I really appreciate what @warpech did (I'm not sure if it was intentional or as a side effect) and I'd like to announce that Content app will be fixed by monday for SC 2.4, in case this will change anything regarding this current issue.

@Mihaiii here is talking about populating the URIs list with the actual object ids from the Content editor. It is not in scope of this issue, but we can do it in future.

**Comment by kegor** [comment]
Closed because required changes was merged in #93.
