### ISSUE TITLE
Only insert blendable URIs as area items

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#160]
From: https://github.com/Starcounter/Launchpad/issues/40#issuecomment-378754522

BlendingProvider should ~~not~~ skip inserting the area item if the URI is not listed in `Blender.ListAllByUris()`. 

BlendingEditor should warn that this URI is not found in the list of blendable URIs, like this:

![all routes uri expanded](https://user-images.githubusercontent.com/566463/38337360-a4ab85ae-386d-11e8-8221-e1f60c7a4b99.png)

**Comment by PatrykSzwer** [comment]
I've done the second part, but TBH I don't really understand the first:
> BlendingProvider should *not* skip inserting the area item if the URI is not listed in Blender.ListAllByUris().

As far as I know, there is no such check in BlendingProvider. Could you clarify more what you meant by that sentence?

**Comment by warpech** [comment]
First of all, sorry for the typo. I meant that it **should skip inserting the area item**.

I mean this method of code: https://github.com/Starcounter/Blending/blob/b98142170b56604f4f295f77858ff9e2d5f80001/src/BlendingProvider/Website/Api/BlendingHandlers.cs#L263

Currently, it sets a blending rule to any `webMap.ForeignUri`. My proposal is to validate if `ForeignUri` registered as blendable by checking if:

- it is present in `Blender.ListAllByUris()` (for example, People app is running and `ForeignUri` equals `/people/partial/person/{?}`)
- it is a mixed URI for a URI that is present in `Blender.ListAllByUris()` (for example, People app is running and `ForeignUri` equals `/people/partial/person/{123}`)

**Comment by PatrykSzwer** [comment]
Actually, just fixing the typo would be explanatory enough 😃 But thank you for good explanation, now I know what you meant.

**Comment by PatrykSzwer** [comment]
One problem came up about this issue: If we skip inserting the area items in BlendingProvider method, then even if user turns on his app with proper URI, It will still not be mapped since currently, as @alemoi told me, there is no indicator that would say, whenever blending rules have changed. 

The best solution right now will be to add a warning to UI when user wants to add URI which doesn't exist in `Blender.ListAllByUris()`, and later when we move blending rules to the database, solution for that should be fairly easily obtainable.

**Comment by PatrykSzwer** [comment]
Closing as done.
