### ISSUE TITLE
Empty page when running Blending

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Blending#166]
### Steps to reproduce
Latest SC develop with latest Blending master. Run and go to: http://localhost:8080/blendingeditor
All HTMLs and JSs are downloaded fine and no errors in console. But the page is blank, nothing is displayed. Run on new database, and http://127.0.0.1:8080/blendingeditor/resetdata didn't help either. 
If I run SignIn alone - it displays itself, but if I then start Blending - then even SignIn is not showing anything.

### Expected result
Some page to be shown visually.

### Actual result
Nothing is shown.

##### Starcounter version 
2.4 latest

##### Involved apps' version
Just Blending app alone is enough.

 
##### Browsers affected

Chrome, Firefox.

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari

### Screenshot
![image](https://user-images.githubusercontent.com/208134/38471632-ff725b1c-3b73-11e8-9625-2e0f8fd60d98.png)

**Comment by alemoi** [comment]
CC @warpech @miyconst @kegor

**Comment by alemoi** [comment]
This is a showstopper for me for this issue: https://github.com/Starcounter/level1/issues/4489#issuecomment-379240526

After all attempts to find the issue with @kegor we didn't succeed. We tried the downloaded version of Starcounter but didn't succeed. `Blending` app still breaks other apps, so nothing is displayed in browser.

**Comment by miyconst** [comment]
@warpech please take care of the issue or assign someone else to do so.

**Comment by warpech** [comment]
@PatrykSzwer could you please take a look at this today? This is high prio.

**Comment by PatrykSzwer** [comment]
We managed to fix the issue and find (maybe not exact but still) a reason.

Turns out that problem was in the Simplified package used by SignIn app. 
SignIn, same as other apps, uses Simplified got from nuget package. Based on it a database is created, including `SystemUserSession` table etc.

Long story:

In @alemoi case, his .dll Simplified NuGet file was somehow corrupted. Visual studio wasn't aware of that, so It didn't try to fix it or download again. This corruption was causing some unexpected behaviors in terms of sessions and probably a lot more classes, but in the same time It wasn't detected as an error, because although corrupted database all apps were building and working correctly. 
After further investigation turns out that after removing obj/bin files from SignIn, Visual Studio wasn't able to build an app again, due to missing Simplified classes (VS found out that somethings wrong with the Simplified package... Better late than never). After removing the Simplified package from the solution by Nuget Package Manager in VS, and installing it again, everything started working again without any additional issues. We don't know what caused the corruption of Simplified file in the first place, but I think It's not specifically Starcounter related. I think it caused so big and hard to find problems because we're using NuGet package as a schema for our database, which is not really popular approach, and this may be more vulnerable on corruption this type than a typical usage of NuGet packages.

Short story:

If you find out that your app doesn't recognize you even if you're logged in, and BlendingProvider is making all apps returning blank screen even with pure and freshly created environment, then probably reinstalling Simplified package in your SignIn app (or whatever other app will be related to your problem) will fix this problem.

**Comment by miyconst** [comment]
@PatrykSzwer thank you for the investigation. Is it possible to identify the faulty Simplified NuGet package?

**Comment by PatrykSzwer** [comment]
We didn't preserve the corrupted file, and also couldn't reproduce it in any way, so I would say that is either impossible or really close to it.

**Comment by PatrykSzwer** [comment]
As I said I don't think its related to specific Simplified package, more to the way that Nuget manager is downloading it and to packages structure itself. But as I said, those are my assumptions based on our investigation and I can't be 100% sure any of those hypotheses.

**Comment by Mihaiii** [comment]
> @PatrykSzwer thank you for the investigation. Is it possible to identify the faulty Simplified NuGet package?

Please take into consideration that at this moment we can't run 2 apps that have different Simplified version (we would get an error right after starting the 2nd app).
