### ISSUE TITLE
REST interface for importing of settings

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#203]
After #181 is done, add a REST `PUT` handler that replaces the current settings with the configuration sent as a JSON payload.

@malx122 reported today on the "App developer experience ref group" meeting that he needs a programmatic way to import the settings.

**Comment by warpech** [comment]
@malx122 says he will need this fast, because he resets the db 20 times a day. We should do it in June.

**Comment by kegor** [comment]
If we are talking about the ability to update the settings using tools such as [Postman](https://www.getpostman.com/), then the solution seems straightforward to me: register the `PUT` handler as an example here: https://github.com/Starcounter/level1/blob/09ebe2cd524f08034acd469059b99804124a648f/src/Starcounter.Administrator/Server/API/RestHandlers.cs#L293 in which the JSON-line will be used to update the settings in the database.

Another question for me here appeared in the fact that I do not see much point in updating the `WebSettings` of the `BlendingEditor`, since they contain only one significant field for turning off the `ViewKeeper`, maybe we are more likely speaking about possible updating settings in any application?

@warpech could you please clarify the final target a little?

**Comment by warpech** [comment]
The user story is that a solution owner would like to install apps on a fresh installation of Starcounter. After the apps are installed, he wants to import Blending app suite settings in a script. Most likely we will push a JSON file to a HTTP endpoint using a tool like cURL.

> Another question for me here appeared in the fact that I do not see much point in updating the WebSettings of the BlendingEditor, since they contain only one significant field for turning off the ViewKeeper, maybe we are more likely speaking about possible updating settings in any application?

We are talking about importing the file that is the result of a manual export in BlendingEditor, with anything that can be expected there.

**Comment by kegor** [comment]
@warpech I've pushed the few lines of code to finish clarifying the final target here: https://github.com/Starcounter/Blending/commit/40f774752a381f7c4c1cc49c30a1d8255120c54c.
And this works like this:
![import-using-put2](https://user-images.githubusercontent.com/17431807/41879102-ba45ed24-78e0-11e8-884f-91abc55b68ca.gif)
Is this looks like right direction?
(I used Postman bc I'm not familiar with the cURL as the script execution tool)

**Comment by warpech** [comment]
Yes, that's it!

**Comment by kegor** [comment]
Closing because related changes were merged in the #252.
