### ISSUE TITLE
Display the key for the composition in the database

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Blending#24]
_Issue moved from CompositionEditor repository: https://github.com/Starcounter/CompositionEditor/issues/31_

When editing the composition, I would like to know the [key](https://github.com/Starcounter/level1/blob/2d6990034e47906453c8108c6191bdf43aa78959/src/Starcounter.Extensions/HTMLComposition.cs#L8) by which it will be saved in the database. 

This way it becomes easier to make notes for exporting/importing of the saved compositions.

Right now the way to do it is to use Chrome Dev Tools Network tab to check the REST API request.

![artboard](https://user-images.githubusercontent.com/566463/28121580-dc624fe2-671b-11e7-91d5-0ad89ada74bc.png)

**Comment by un-tone** [comment]
The issue seems to be outdated since `HTMLComposition` is not used anymore and the current data model for compositions does not contain the `Key` property or any alternative. It means that the data model does not have any representative properties which would be useful in the Composition Editor view.

I see two ways:

1. Close the issue as irrelevant.
2. Add a new property to the data model in level1.

**Comment by kegor** [comment]
Thank you @un-tone for clarification, @warpech, @PatrykSzwer wdyt?

**Comment by PatrykSzwer** [comment]
Depends, if we still think that this feature is needed and will be used by users. @warpech was the initiator of this idea so I'll let him make the decision.

**Comment by warpech** [comment]
The purpose of this change is to remove the need of using Starcounter DevTools to find out what are the views that take part in this particular composition and where it is stored in the db.

This issue is not obsolete, but since we changed the data model, the message needs to be adapted. I believe it should be something like below.

Most information should be already in the JSON, if I recall correctly only the object ID of `HtmlViewComposition` should be added to it.

![new](https://user-images.githubusercontent.com/566463/40312392-106409d2-5d13-11e8-9d2e-d8081c95f7c0.png)

**Comment by alshakero** [comment]
Closing as done in https://github.com/Starcounter/Blending/pull/205 & https://github.com/Starcounter/Blending/pull/244.
